name: mqtt_demo
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  mqtt_client: ^10.2.0
  provider: ^6.1.2
  get_it: ^7.6.7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
